name = "ceramientas-push"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "BRIDGE"
class_name = "MqttPushBridge"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MqttPushBridge"]

[[kv_namespaces]]
binding = "SUBS"
id = "59bdf61299cf4e0ca5bd9f1603b583c2"
